metadata:
  logo: "https://raw.githubusercontent.com/openpeeps/tim/main/.github/timV2.png"
  logo_keep_gradient: true
  title: "Tim Engine Documentation"
  description: "Documentation page for Tim Engine - a powerful template engine and scripting language for developers."
  keywords: ["tim", "template", "templating", "template engine", "scripting language"]

appearance:
  show_theme_switcher: true
  default_theme: "system"
  show_toggle_left_sidebar: true
  show_toggle_right_sidebar: true
  container_width: "col-lg-10 mx-auto"
  content_width: "col-lg-7"
  background_noise_opacity: 0.3

git:
  enable_versioning: false
  enable_contributors_info: false

header:
  search:
    enable: true
    index_meta_data: true
    index_page_titles: true

content:
  allow_raw_html_tags:
    - "b"
    - "i"
    - "strong"
    - "em"
    - "a"
    - "p"
    - "ul"
    - "ol"
    - "li"

  show_last_updated: true
  last_date_updated_format: "yyyy-MM-dd HH:mm:ss"
  enable_auto_format_links: true
  bottom_navigation: true
  code_highlight_theme: "default"
  share_ai_buttons: true
  share_buttons_ai_providers:
    - label: "ChatGPT"
      url: "https://chat.openai.com"
      description: "Share with ChatGPT"
    - label: "Claude"
      url: "https://claude.ai"
      description: "Share with Claude"
    - label: "Gemini"
      url: "https://gemini.google.com"
      description: "Share with Gemini"
    - label: "Copilot"
      url: "https://github.com/copilot/"
      description: "Share with GitHub Copilot"


navbar:
  - title: "GitHub Repository"
    url: "https://github.com/openpeeps/tim"
    icon: ""
  - title: "API Reference"
    url: "https://openpeeps.github.io/tim/theindex.html"
    icon: "icon-book"

sidebar_navigation:
  - name: "Getting Started"
    items:
      - title: "Introduction"
        url: "/"
        icon: ""
      - title: "Installation"
        url: "/install"
        icon: "icon-download"

  - name: "Language"
    items:
      - title: "Syntax"
        url: "/language/syntax"
      - title: "Variables"
        url: "/language/variables"
      - title: "Functions"
        url: "/language/functions"
      - title: "Macros"
        url: "/language/macros"
      - title: "Control Flow"
        url: "/language/control-flow"


  - name: "Standard Library"
    items:
      - title: "System"
        url: "/lib/system"
      - title: "Math"
        url: "/lib/math"
      - title: "Strings"
        url: "/lib/strings"
      - title: "Arrays"
        url: "/lib/arrays"
      - title: "Objects"
        url: "/lib/objects"
  
  - name: "Package Manager"
    items:
      - title: "Manage Packages"
        url: "/package-manager"

      - title: "Create a Package"
        url: "/package-manager/create-package"

      - title: "Publish a Package"
        url: "/package-manager/publish-package"

extra_sections:
  left_sidebar:
    - content: |
        <div class="card border-2 rounded-4" style="border-style: dotted;">
          <div class="card-body small p-2 lh-sm justify-content-center d-flex align-items-center user-select-none">
            <div class="bg-warning flex-shrink-0 rounded-pill p-1 me-2">
              <img class="img-fluid" src="/assets/bug-icon.png" width="32px" height="32px" alt="Bug Icon">
            </div>
            <p class="mb-0 small d-inline">
              <strong>Found a bug?</strong><br>Create a new issue on <a href="https://github.com/openpeeps/booyaka/issues" class="text-link d-inline-block bg-dark" target="_blank">GitHub</a>
            </p>
          </div>
        </div>
  right_sidebar:
    - content: |
        <div class="card border-2 rounded-4 me-3" style="border-style: dotted;">
          <div class="card-body small p-4 lh-sm user-select-none">
            <img class="img-fluid" src="/assets/hetzner-logo.svg?m=1764328696" width="100%" alt="Hetzner Logo">
            <p class="mt-3">
              Get € 20.00 free credit on Hetzner Cloud with our link!<br>
            </p>
            <p class="mb-0 text-center">
              <a href="https://hetzner.cloud/?ref=Hm0mYGM9NxZ4" class="btn btn-sm py-1 rounded-pill bg-dark d-inline-block" target="_blank">Sign up to Hetzner Cloud</a>
            </p>
          </div>
        </div>

footer:
  text: ""
  links:
    - title: "GitHub"
      url: "https://github.com/example"
      icon: "icon-brand-github"